bloodpressure/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("measurements/", include("measurements.urls")),
]

measurements/urls.py
from django.urls import path
from . import views

app_name = "measurements"
urlpatterns = [
    path("", views.list, name="list"),
    path("<int:id>", views.details, name="details"),

]

measurements/models.py
from django.db import models

# Create your models here.

class Measurement(models.Model):
    date = models.DateTimeField()
    diastolic = models.IntegerField()
    systolic = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

measurements/views.py
from datetime import datetime
from django.shortcuts import render
from .services import MeasurementService as service
# Create your views here.

def list(request):

    if request.method == "GET":
        print(request.GET)


    if request.method == "POST":
        print(request.POST)
        service.create(
            date=datetime.fromisoformat(request.POST.get("mes_date")),
            systolic=request.POST.get("mes_systolic"),
            diastolic=request.POST.get("mes_diastolic")
        )

    ms = service.list()


    # if request.method == "POST":
    #     Measurement.objects.create(
    #         date=request.POST.get("mes_date"),
    #         systolic=request.POST.get("mes_systolic"),
    #         diastolic=request.POST.get('mes_diastolic'),
    #     )
    #
    # ms = Measurement.objects.all()

    return render(
        request, 
        "measurements/list.html",
        {"measurements": ms}
    )



def details(request, id): pass

templates/measurements/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Pomiary {{ user }}</h1>
    <table>
        <thead>
            <th>data</th>
            <th>systolic</th>
            <th>diastolic</th>
        </thead>
        <tbody>
            {% for m in measurements %}
            <tr>
                <td><a href="{% url 'measurements:details' m.id %}">{{m.date}}</a></td>
                <td>{{m.systolic}}</td>
                <td>{{m.diastolic}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div>
        <form method="POST">
            {% csrf_token %} 
            <p>
                <label for="m_date">Data pomiaru</label>
                <input type="datetime-local" id="m_date" name="mes_date"> 
            </p>
            <p>
                <label for="m_systolic">Skurczowe</label>
                <input type="number" id="m_systolic" name="mes_systolic"> 
            </p>
            <p>
                <label for="m_diastolic">Rozkurczowe</label>
                <input type="number" id="m_diastolic" name="mes_diastolic"> 
            </p>
            <p>
                <input type="submit" value="send">
            </p>
        </form>

    </div>

</body>
</html>